import axios from 'axios';

const FETCHING_FRIENDS = 'FETCHING_FRIENDS'
const FRIENDS_FETCHED = 'FRIENDS_FETCHED'
const FRIENDS_SAVED = 'FRIENDS_SAVED'
const SAVING_FRIENDS = 'SAVING_FRIENDS'
const UPDATING_FRIEND = 'UPDATING_FRIEND'
const FRIEND_UPDATED = 'FRIEND_UPDATED'
const DELETING_FRIEND = 'DELETING_FRIEND'
const FRIEND_DELETED = 'FRIEND_DELETED'
const FRIENDS = 'FRIENDS'
const ERROR = 'ERROR'
