export const FETCHINGFRIENDS = 'FETCHINGFRIENDS';
export const FETCHEDFRIENDS = 'FETCHEDFRIENDS';
export const ERROR = 'ERROR';
export const ADDINGFRIEND = 'ADDINGFRIEND';
export const ADDEDFRIEND = 'ADDEDFRIEND';
export const DELETINGFRIEND = 'DELETINGFRIEND';
export const DELETEDFRIEND = 'DELETEFRIEND';
export const RESET = 'RESET';
