export {
    FETCHING_FRIENDS_START,
    FETCHING_FRIENDS_SUCCESS,
    FETCHING_FRIENDS_FAILURE,

    ADD_FRIEND_START,
    ADD_FRIEND_SUCCESS,
    ADD_FRIEND_FAILURE,

    REMOVE_FRIEND_START,
    REMOVE_FRIEND_SUCCESS,
    REMOVE_FRIEND_FAILURE,

    getFriends,
    addNewFriend,
    removeFriend,
} from './friendsActions';