import axios from "axios";


export const FETCHING_FRIEND_START = "FETCHING_FRIEND_START";
export const FETCHING_FRIEND_SUCCESS = "FETCHING_FRIEND_SUCCESS";
export const FETCHING_FRIEND_FAILURE = "FETCHING_FRIEND_FAILURE";

